### ISSUE TITLE
Error if trying to use library before body is found

### ISSUE THREAD

**Issue by ispal** [caroso1222/notyf#67]
Hi,

I just noticed that this library doesn't work if it's used in a script included in the `head` section of the page (before the body is in place). It also requires script tag to not have `defer` attribute.
 
It boils down to this line
https://github.com/caroso1222/notyf/blob/27cd61ad8726f21fcab2add9b58799d92aac9d2f/src/notyf.view.ts#L34

It will give the following error: `Cannot read property 'appendChild' of null` which basically means that the body is not there yet and can't append to it. It works if I move script tag to bottom or use `defer` attribute, but in my case I can't use neither. 

Is there a way to fix this?

**Comment by caroso1222** [comment]
Hey! Hmm good catch. Just wondering, why do you need it to work on the head? scripts like this library are generally meant to be placed on the body bottom so that it doesn't block initial rendering and can also make use of the body.

Can you please give a bit more context on why you need it on the head? Maybe there's another way around.

**Comment by ispal** [comment]
It's just in my local development setup (CMS site). I have it in the head because otherwise there's a flash of unstyled content. I have a webpack dev server in use and the styles are injected when the script is executed. It's a minor issue but still a bit annoying 😄. It's kind of my issue maybe now when I think. I just wanted to let you know.
